# Generated by Django 4.1.2 on 2022-10-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_title_product_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titre',
            new_name='title',
        ),
    ]
